######TESTING REPORT######

Date: Sat Aug 21 23:43:26 CDT 2021 

---UNITTEST---

test_dequip (tests.test_armor.ArmorTest) ... FAIL
test_equip (tests.test_armor.ArmorTest) ... FAIL
test_init (tests.test_armor.ArmorTest) ... FAIL
test_printToFile (tests.test_armor.ArmorTest) ... ok
test__str__ (tests.test_equipment.EquipmentTest) ... ok
test_details (tests.test_equipment.EquipmentTest) ... ok
test_export1 (tests.test_equipment.EquipmentTest) ... ok
test_export2 (tests.test_equipment.EquipmentTest) ... ok
test_init (tests.test_equipment.EquipmentTest) ... ok
test_printToFile (tests.test_equipment.EquipmentTest) ... ok

======================================================================
FAIL: test_dequip (tests.test_armor.ArmorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/jevin/OneDrive/Documents/CODING/Dev/FUNCLG/FUNCLG/tests/test_armor.py", line 43, in test_dequip
    self.fail("Incomplete Test")
AssertionError: Incomplete Test

======================================================================
FAIL: test_equip (tests.test_armor.ArmorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/jevin/OneDrive/Documents/CODING/Dev/FUNCLG/FUNCLG/tests/test_armor.py", line 39, in test_equip
    self.fail("Incomplete Test")
AssertionError: Incomplete Test

======================================================================
FAIL: test_init (tests.test_armor.ArmorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/jevin/OneDrive/Documents/CODING/Dev/FUNCLG/FUNCLG/tests/test_armor.py", line 35, in test_init
    self.fail("Incomplete Test")
AssertionError: Incomplete Test

----------------------------------------------------------------------
Ran 10 tests in 0.003s

FAILED (failures=3)

---Flake 8----

./core/armor.py:44:7: T101 fixme found (TODO)
./core/armor.py:45:7: T101 fixme found (TODO)
./core/equipment.py:52:11: T101 fixme found (TODO)
./tests/test_armor.py:34:11: T101 fixme found (TODO)
./tests/test_armor.py:38:11: T101 fixme found (TODO)
./tests/test_armor.py:42:11: T101 fixme found (TODO)
6
